/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef _MGMErfcFunction_hh_
#define _MGMErfcFunction_hh_

#include "RooAbsReal.h"
#include "RooRealProxy.h"
 
class MGMErfcFunction : public RooAbsReal {
public:
  MGMErfcFunction() {} ; 
  MGMErfcFunction(const char *name, const char *title,
	      RooAbsReal& _energy,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma);
  MGMErfcFunction(const MGMErfcFunction& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MGMErfcFunction(*this,newname); }
  inline virtual ~MGMErfcFunction() { }

protected:

  RooRealProxy fEnergy ;
  RooRealProxy fMean ;
  RooRealProxy fSigma ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MGMErfcFunction,1) // Your description goes here...
};
 
#endif
