 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "MGMWimpTimeFunction.hh" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include <math.h> 
 #include "TMath.h" 

 ClassImp(MGMWimpTimeFunction) 

 MGMWimpTimeFunction::MGMWimpTimeFunction(const char *name, const char *title, 
                        RooAbsReal& _velocity_0,
                        RooAbsReal& _velocity_1,
                        RooAbsReal& _time) :
   RooAbsReal(name,title), 
   velocity_0("velocity_0","velocity_0",this,_velocity_0),
   velocity_1("velocity_1","velocity_1",this,_velocity_1),
   time("time","time",this,_time)
 { 
 } 


 MGMWimpTimeFunction::MGMWimpTimeFunction(const MGMWimpTimeFunction& other, const char* name) :  
   RooAbsReal(other,name), 
   velocity_0("velocity_0",this,other.velocity_0),
   velocity_1("velocity_1",this,other.velocity_1),
   time("time",this,other.time)
 { 
 } 



 Double_t MGMWimpTimeFunction::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return velocity_0 + velocity_1*TMath::Sin(TMath::TwoPi()*time); 
 } 



