/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef _MGMWimpHelmFFSquared_hh_
#define _MGMWimpHelmFFSquared_hh_ 1

#include "MGMVWimpFormFactor.hh"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
 
class MGMWimpHelmFFSquared : public MGMVWimpFormFactor {
public:
  MGMWimpHelmFFSquared() {} ; 
  MGMWimpHelmFFSquared(const char *name, const char *title,
	      RooAbsReal& _q,
	      RooAbsReal& _r_sub_n,
	      RooAbsReal& _s);
  MGMWimpHelmFFSquared(const MGMWimpHelmFFSquared& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MGMWimpHelmFFSquared(*this,newname); }
  inline virtual ~MGMWimpHelmFFSquared() { }

protected:

  RooRealProxy q ;
  RooRealProxy r_sub_n ;
  RooRealProxy s ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MGMWimpHelmFFSquared,1) // Your description goes here...
};
 
#endif
