 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "MGMWimpHelmFFSquared.hh" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include <math.h> 
 #include "TMath.h" 

 ClassImp(MGMWimpHelmFFSquared) 

 MGMWimpHelmFFSquared::MGMWimpHelmFFSquared(const char *name, const char *title, 
                        RooAbsReal& _q,
                        RooAbsReal& _r_sub_n,
                        RooAbsReal& _s) :
   MGMVWimpFormFactor(name,title), 
   q("q","q",this,_q),
   r_sub_n("r_sub_n","r_sub_n",this,_r_sub_n),
   s("s","s",this,_s)
 { 
 } 


 MGMWimpHelmFFSquared::MGMWimpHelmFFSquared(const MGMWimpHelmFFSquared& other, const char* name) :  
   MGMVWimpFormFactor(other,name), 
   q("q",this,other.q),
   r_sub_n("r_sub_n",this,other.r_sub_n),
   s("s",this,other.s)
 { 
 } 



 Double_t MGMWimpHelmFFSquared::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t q_times_r = q*r_sub_n;
   Double_t temp = (q_times_r <= 2) ? 
            (1-TMath::Power(q_times_r,2)/5. + 3*TMath::Power(q_times_r,4)/175.
             - 4*TMath::Power(q_times_r, 6)/4725.) :
            9*TMath::Power(
              (TMath::Sin(q_times_r) - q_times_r*TMath::Cos(q_times_r))/
              (TMath::Power(q_times_r, 3)),2);
   return temp*TMath::Exp(-TMath::Power(q*s,2));
 } 

